/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simpus;

import simpus.FormBuku;
import simpus.FormDashboard;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import simpus.FormKategori;
import simpus.FormSkripsi;

/**
 *
 * @author Ailsa
 */
public class GUIUtama extends javax.swing.JFrame {

    /**
     * Creates new form GUIUtama
     */
    public GUIUtama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSidebar = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnKanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnTampil = new javax.swing.JPanel();
        pnUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        pnSidebar.setBackground(new java.awt.Color(255, 255, 255));

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setPreferredSize(new java.awt.Dimension(100, 70));
        pnMenu.setLayout(new javax.swing.BoxLayout(pnMenu, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Si MPus.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Sistem Manajemen");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Perpustakaan UINSA");

        javax.swing.GroupLayout pnSidebarLayout = new javax.swing.GroupLayout(pnSidebar);
        pnSidebar.setLayout(pnSidebarLayout);
        pnSidebarLayout.setHorizontalGroup(
            pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSidebarLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSidebarLayout.createSequentialGroup()
                        .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        pnSidebarLayout.setVerticalGroup(
            pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSidebarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSidebarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(pnSidebar, java.awt.BorderLayout.LINE_START);

        pnKanan.setBackground(new java.awt.Color(255, 255, 255));
        pnKanan.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(229, 183, 137));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnKanan.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnTampil.setBackground(new java.awt.Color(245, 245, 245));

        pnUtama.setBackground(new java.awt.Color(255, 255, 255));
        pnUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnTampilLayout = new javax.swing.GroupLayout(pnTampil);
        pnTampil.setLayout(pnTampilLayout);
        pnTampilLayout.setHorizontalGroup(
            pnTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTampilLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pnTampilLayout.setVerticalGroup(
            pnTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTampilLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pnKanan.add(pnTampil, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnKanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUIUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnKanan;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnSidebar;
    private javax.swing.JPanel pnTampil;
    private javax.swing.JPanel pnUtama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon IconDashboard = new ImageIcon(getClass().getResource("/gambar/IconDashboard.png"));
        ImageIcon IconPengguna = new ImageIcon(getClass().getResource("/gambar/IconPengguna.png"));
        ImageIcon IconData = new ImageIcon(getClass().getResource("/gambar/IconData.png"));
        ImageIcon IconBuku = new ImageIcon(getClass().getResource("/gambar/IconBuku.png"));
        ImageIcon IconSkripsi = new ImageIcon(getClass().getResource("/gambar/IconSkripsi.png"));
        ImageIcon IconKategori = new ImageIcon(getClass().getResource("/gambar/IconKategori.png"));
        ImageIcon IconTransaksi = new ImageIcon(getClass().getResource("/gambar/IconTransaksi.png"));
        ImageIcon IconPeminjaman = new ImageIcon(getClass().getResource("/gambar/IconPeminjaman.png"));
        ImageIcon IconPengembalian = new ImageIcon(getClass().getResource("/gambar/IconPengembalian.png"));
        ImageIcon IconSetting = new ImageIcon(getClass().getResource("/gambar/IconSetting.png"));
        ImageIcon IconLaporan = new ImageIcon(getClass().getResource("/gambar/iconLaporan.png"));

        MenuItem menuBuku = new MenuItem(null, true, IconBuku, "Data Buku", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new FormBuku());
                pnUtama.repaint();
                pnUtama.revalidate();

            }
        });

        MenuItem menuSkripsi = new MenuItem(null, true, IconSkripsi, "Data Skripsi", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new FormSkripsi());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem menuKategori = new MenuItem(null, true, IconKategori, "Kategori", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new FormKategori());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem menuPinjamB = new MenuItem(null, true, IconBuku, "Pinjam Buku",new ActionListener() {
        public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new FormPeminjamanBuku());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem menuPinjamS = new MenuItem(null, true, IconSkripsi, "Pinjam Skripsi",new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new FormPeminjamanSkripsi());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem menuLBuku = new MenuItem(null, true, IconBuku, "Buku", new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new FormLaporanBuku());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem menuLSkripsi = new MenuItem(null, true, IconSkripsi, "Skripsi",new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new FormLaporanSkripsi());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem menuPBuku = new MenuItem(null, true, IconBuku, "Buku", null);
        MenuItem menuPSkripsi = new MenuItem(null, true, IconSkripsi, "Skripsi", null);

        MenuItem menuDashboard = new MenuItem(IconDashboard, false, null, "Home", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new FormDashboard());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem menuPengguna = new MenuItem(IconPengguna, false, null, "Pengguna", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pnUtama.removeAll();
                pnUtama.add(new FormPengguna1());
                pnUtama.repaint();
                pnUtama.revalidate();
            }
        });
        MenuItem menuData = new MenuItem(IconData, false, null, "Data", null, menuBuku, menuSkripsi, menuKategori);
        MenuItem menuPeminjaman = new MenuItem(IconPeminjaman, false, null, "Peminjaman", null, menuPinjamB, menuPinjamS);
        MenuItem menuLaporan = new MenuItem(IconLaporan, false, null, "Laporan Data", null, menuLBuku, menuLSkripsi);
        MenuItem menuLaporanP = new MenuItem(IconLaporan, false, null, "Laporan Peminjaman", null, menuPBuku, menuPSkripsi);
        MenuItem menuSetting = new MenuItem(IconSetting, false, null, "Pengaturan", null);

        addMenu(menuDashboard, menuPengguna, menuData, menuPeminjaman, menuLaporan, menuLaporanP, menuSetting);

    }

    private void addMenu(MenuItem... menu) {
        for (int i = 0; i < menu.length; i++) {
            pnMenu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }

        }
        pnMenu.revalidate();
    }
}
