/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Simpus;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Ailsa
 */
public class MenuUtama extends javax.swing.JFrame {

    int xx, xy;

    public MenuUtama() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSide = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnDB = new javax.swing.JPanel();
        pnLine = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btMenu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnData = new javax.swing.JPanel();
        pnLine1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btDatabuku = new javax.swing.JLabel();
        pnPinjam = new javax.swing.JPanel();
        pnLine2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btPinjam = new javax.swing.JLabel();
        pnDS = new javax.swing.JPanel();
        pnLine3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btDataskripsi = new javax.swing.JLabel();
        pnAng = new javax.swing.JPanel();
        pnLine4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btAng = new javax.swing.JLabel();
        pnPetugas = new javax.swing.JPanel();
        pnLine5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btPetugas = new javax.swing.JLabel();
        pnKat = new javax.swing.JPanel();
        pnLine6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btKat = new javax.swing.JLabel();
        pnKanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnTampil = new javax.swing.JPanel();
        pnUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 768));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnSide.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambaran/Si MPus.jpg"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Menu");

        pnDB.setBackground(new java.awt.Color(255, 255, 255));

        pnLine.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnLineLayout = new javax.swing.GroupLayout(pnLine);
        pnLine.setLayout(pnLineLayout);
        pnLineLayout.setHorizontalGroup(
            pnLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLineLayout.setVerticalGroup(
            pnLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambaran/Home.png"))); // NOI18N

        btMenu.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btMenu.setForeground(new java.awt.Color(102, 102, 102));
        btMenu.setText("Dashboard");
        btMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnDBLayout = new javax.swing.GroupLayout(pnDB);
        pnDB.setLayout(pnDBLayout);
        pnDBLayout.setHorizontalGroup(
            pnDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDBLayout.createSequentialGroup()
                .addComponent(pnLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        pnDBLayout.setVerticalGroup(
            pnDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnDBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Sistem Manajemen");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Perpustakaan UINSA");

        pnData.setBackground(new java.awt.Color(255, 255, 255));

        pnLine1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnLine1Layout = new javax.swing.GroupLayout(pnLine1);
        pnLine1.setLayout(pnLine1Layout);
        pnLine1Layout.setHorizontalGroup(
            pnLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine1Layout.setVerticalGroup(
            pnLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambaran/Book.png"))); // NOI18N

        btDatabuku.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btDatabuku.setForeground(new java.awt.Color(102, 102, 102));
        btDatabuku.setText("Buku");
        btDatabuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDatabukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDatabukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDatabukuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnDataLayout = new javax.swing.GroupLayout(pnData);
        pnData.setLayout(pnDataLayout);
        pnDataLayout.setHorizontalGroup(
            pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDataLayout.createSequentialGroup()
                .addComponent(pnLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(btDatabuku, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDataLayout.setVerticalGroup(
            pnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btDatabuku, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPinjam.setBackground(new java.awt.Color(255, 255, 255));

        pnLine2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnLine2Layout = new javax.swing.GroupLayout(pnLine2);
        pnLine2.setLayout(pnLine2Layout);
        pnLine2Layout.setHorizontalGroup(
            pnLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine2Layout.setVerticalGroup(
            pnLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambaran/Peminjaman.png"))); // NOI18N

        btPinjam.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btPinjam.setForeground(new java.awt.Color(102, 102, 102));
        btPinjam.setText("Peminjaman");
        btPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPinjamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPinjamMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnPinjamLayout = new javax.swing.GroupLayout(pnPinjam);
        pnPinjam.setLayout(pnPinjamLayout);
        pnPinjamLayout.setHorizontalGroup(
            pnPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPinjamLayout.createSequentialGroup()
                .addComponent(pnLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(btPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        pnPinjamLayout.setVerticalGroup(
            pnPinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnPinjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnDS.setBackground(new java.awt.Color(255, 255, 255));

        pnLine3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnLine3Layout = new javax.swing.GroupLayout(pnLine3);
        pnLine3.setLayout(pnLine3Layout);
        pnLine3Layout.setHorizontalGroup(
            pnLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine3Layout.setVerticalGroup(
            pnLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambaran/iconSkripsi.png"))); // NOI18N

        btDataskripsi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btDataskripsi.setForeground(new java.awt.Color(102, 102, 102));
        btDataskripsi.setText("Skripsi");
        btDataskripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDataskripsiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDataskripsiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDataskripsiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnDSLayout = new javax.swing.GroupLayout(pnDS);
        pnDS.setLayout(pnDSLayout);
        pnDSLayout.setHorizontalGroup(
            pnDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDSLayout.createSequentialGroup()
                .addComponent(pnLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(btDataskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        pnDSLayout.setVerticalGroup(
            pnDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLine3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnDSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btDataskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnAng.setBackground(new java.awt.Color(255, 255, 255));

        pnLine4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnLine4Layout = new javax.swing.GroupLayout(pnLine4);
        pnLine4.setLayout(pnLine4Layout);
        pnLine4Layout.setHorizontalGroup(
            pnLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine4Layout.setVerticalGroup(
            pnLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambaran/Home.png"))); // NOI18N

        btAng.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btAng.setForeground(new java.awt.Color(102, 102, 102));
        btAng.setText("Anggota");
        btAng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAngMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAngMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btAngMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnAngLayout = new javax.swing.GroupLayout(pnAng);
        pnAng.setLayout(pnAngLayout);
        pnAngLayout.setHorizontalGroup(
            pnAngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAngLayout.createSequentialGroup()
                .addComponent(pnLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btAng, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        pnAngLayout.setVerticalGroup(
            pnAngLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLine4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnAngLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAng, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnPetugas.setBackground(new java.awt.Color(255, 255, 255));

        pnLine5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnLine5Layout = new javax.swing.GroupLayout(pnLine5);
        pnLine5.setLayout(pnLine5Layout);
        pnLine5Layout.setHorizontalGroup(
            pnLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine5Layout.setVerticalGroup(
            pnLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambaran/Home.png"))); // NOI18N

        btPetugas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btPetugas.setForeground(new java.awt.Color(102, 102, 102));
        btPetugas.setText("Petugas");
        btPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPetugasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPetugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPetugasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnPetugasLayout = new javax.swing.GroupLayout(pnPetugas);
        pnPetugas.setLayout(pnPetugasLayout);
        pnPetugasLayout.setHorizontalGroup(
            pnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPetugasLayout.createSequentialGroup()
                .addComponent(pnLine5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        pnPetugasLayout.setVerticalGroup(
            pnPetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLine5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnPetugasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnKat.setBackground(new java.awt.Color(255, 255, 255));

        pnLine6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnLine6Layout = new javax.swing.GroupLayout(pnLine6);
        pnLine6.setLayout(pnLine6Layout);
        pnLine6Layout.setHorizontalGroup(
            pnLine6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        pnLine6Layout.setVerticalGroup(
            pnLine6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambaran/iconSkripsi.png"))); // NOI18N

        btKat.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btKat.setForeground(new java.awt.Color(102, 102, 102));
        btKat.setText("Kategori");
        btKat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btKatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btKatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btKatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnKatLayout = new javax.swing.GroupLayout(pnKat);
        pnKat.setLayout(pnKatLayout);
        pnKatLayout.setHorizontalGroup(
            pnKatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKatLayout.createSequentialGroup()
                .addComponent(pnLine6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(btKat, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        pnKatLayout.setVerticalGroup(
            pnKatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLine6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnKatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btKat, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnSideLayout = new javax.swing.GroupLayout(pnSide);
        pnSide.setLayout(pnSideLayout);
        pnSideLayout.setHorizontalGroup(
            pnSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSideLayout.createSequentialGroup()
                .addGroup(pnSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnSideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnSideLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnSideLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(pnSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(20, 20, 20)
                                    .addGroup(pnSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)))
                                .addComponent(pnData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnAng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnPetugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnSideLayout.setVerticalGroup(
            pnSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSideLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnSideLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnAng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(pnSide, java.awt.BorderLayout.LINE_START);

        pnKanan.setBackground(new java.awt.Color(255, 255, 255));
        pnKanan.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(229, 183, 137));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnKanan.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnTampil.setBackground(new java.awt.Color(245, 245, 245));

        pnUtama.setBackground(new java.awt.Color(255, 255, 255));
        pnUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnTampilLayout = new javax.swing.GroupLayout(pnTampil);
        pnTampil.setLayout(pnTampilLayout);
        pnTampilLayout.setHorizontalGroup(
            pnTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTampilLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pnTampilLayout.setVerticalGroup(
            pnTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTampilLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pnKanan.add(pnTampil, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnKanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMenuMouseEntered
        pnDB.setBackground(new Color(250, 250, 250));
        pnLine.setBackground(new Color(229, 183, 137));
    }//GEN-LAST:event_btMenuMouseEntered

    private void btMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMenuMouseExited
        pnDB.setBackground(new Color(255, 255, 255));
        pnLine.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btMenuMouseExited

    private void btMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMenuMouseClicked
        pnDB.setBackground(new Color(240, 240, 240));
        pnLine.setBackground(new Color(229, 183, 137));

        pnUtama.removeAll();
        pnUtama.add(new FormDashboard());
        pnUtama.repaint();
        pnUtama.revalidate();

    }//GEN-LAST:event_btMenuMouseClicked

    private void btDatabukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDatabukuMouseExited
        pnData.setBackground(new Color(255, 255, 255));
        pnLine1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btDatabukuMouseExited

    private void btDatabukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDatabukuMouseEntered
        pnData.setBackground(new Color(250, 250, 250));
        pnLine1.setBackground(new Color(229, 183, 137));
    }//GEN-LAST:event_btDatabukuMouseEntered

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPinjamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btPinjamMouseClicked

    private void btPinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPinjamMouseEntered
        pnPinjam.setBackground(new Color(250, 250, 250));
        pnLine2.setBackground(new Color(229, 183, 137));
    }//GEN-LAST:event_btPinjamMouseEntered

    private void btPinjamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPinjamMouseExited
        pnPinjam.setBackground(new Color(255, 255, 255));
        pnLine2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btPinjamMouseExited

    private void btDataskripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDataskripsiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btDataskripsiMouseClicked

    private void btDataskripsiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDataskripsiMouseEntered
        pnDS.setBackground(new Color(250, 250, 250));
        pnLine3.setBackground(new Color(229, 183, 137));
    }//GEN-LAST:event_btDataskripsiMouseEntered

    private void btDataskripsiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDataskripsiMouseExited
        pnDS.setBackground(new Color(255, 255, 255));
        pnLine3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btDataskripsiMouseExited

    private void btDatabukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDatabukuMouseClicked
        pnData.setBackground(new Color(240, 240, 240));
        pnLine1.setBackground(new Color(229, 183, 137));

        pnUtama.removeAll();
        pnUtama.add(new FormBuku());
        pnUtama.repaint();
        pnUtama.revalidate();

    }//GEN-LAST:event_btDatabukuMouseClicked

    private void btAngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAngMouseClicked
        pnAng.setBackground(new Color(240, 240, 240));
        pnLine4.setBackground(new Color(229, 183, 137));

        pnUtama.removeAll();
        pnUtama.add(new FormAnggota());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btAngMouseClicked

    private void btAngMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAngMouseEntered
        pnAng.setBackground(new Color(250, 250, 250));
        pnLine4.setBackground(new Color(229, 183, 137));
    }//GEN-LAST:event_btAngMouseEntered

    private void btAngMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAngMouseExited
        pnAng.setBackground(new Color(255, 255, 255));
        pnLine4.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btAngMouseExited

    private void btPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPetugasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btPetugasMouseClicked

    private void btPetugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPetugasMouseEntered
        pnPetugas.setBackground(new Color(250, 250, 250));
        pnLine5.setBackground(new Color(229, 183, 137));
    }//GEN-LAST:event_btPetugasMouseEntered

    private void btPetugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPetugasMouseExited
        pnPetugas.setBackground(new Color(255, 255, 255));
        pnLine5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btPetugasMouseExited

    private void btKatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKatMouseClicked
        pnKat.setBackground(new Color(240, 240, 240));
        pnLine6.setBackground(new Color(229, 183, 137));

        // Mengganti panel utama dengan FormKategori
        pnUtama.removeAll();
        pnUtama.add(new FormKategori());
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btKatMouseClicked

    private void btKatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKatMouseEntered
        pnKat.setBackground(new Color(250, 250, 250));
        pnLine6.setBackground(new Color(229, 183, 137));
    }//GEN-LAST:event_btKatMouseEntered

    private void btKatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKatMouseExited
        pnKat.setBackground(new Color(255, 255, 255));
        pnLine6.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btKatMouseExited

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btAng;
    private javax.swing.JLabel btDatabuku;
    private javax.swing.JLabel btDataskripsi;
    private javax.swing.JLabel btKat;
    private javax.swing.JLabel btMenu;
    private javax.swing.JLabel btPetugas;
    private javax.swing.JLabel btPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnAng;
    private javax.swing.JPanel pnDB;
    private javax.swing.JPanel pnDS;
    private javax.swing.JPanel pnData;
    private javax.swing.JPanel pnKanan;
    private javax.swing.JPanel pnKat;
    private javax.swing.JPanel pnLine;
    private javax.swing.JPanel pnLine1;
    private javax.swing.JPanel pnLine2;
    private javax.swing.JPanel pnLine3;
    private javax.swing.JPanel pnLine4;
    private javax.swing.JPanel pnLine5;
    private javax.swing.JPanel pnLine6;
    private javax.swing.JPanel pnPetugas;
    private javax.swing.JPanel pnPinjam;
    private javax.swing.JPanel pnSide;
    private javax.swing.JPanel pnTampil;
    private javax.swing.JPanel pnUtama;
    // End of variables declaration//GEN-END:variables
}
  

    
       

