-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.buku
(
    id_buku character(20) COLLATE pg_catalog."default" NOT NULL,
    isbn character(50) COLLATE pg_catalog."default",
    judul character varying(100) COLLATE pg_catalog."default",
    subjudul character varying(100) COLLATE pg_catalog."default",
    pengarang character varying(100) COLLATE pg_catalog."default",
    penerbit character varying(100) COLLATE pg_catalog."default",
    tahun character varying(100) COLLATE pg_catalog."default",
    halaman character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT pk_buku PRIMARY KEY (id_buku)
);

CREATE TABLE IF NOT EXISTS public.kategori
(
    id_kategori character(4) COLLATE pg_catalog."default" NOT NULL,
    kategori character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT pk_kategori PRIMARY KEY (id_kategori)
);

CREATE TABLE IF NOT EXISTS public.kategori_buku
(
    id_buku character(11) COLLATE pg_catalog."default" NOT NULL,
    id_kategori character(4) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_kategori_buku PRIMARY KEY (id_buku, id_kategori)
);

CREATE TABLE IF NOT EXISTS public.kategori_skripsi
(
    id_skripsi character(11) COLLATE pg_catalog."default" NOT NULL,
    id_kategori character(4) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_kategori_skripsi PRIMARY KEY (id_skripsi, id_kategori)
);

CREATE TABLE IF NOT EXISTS public.login
(
    id_login character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nama character varying(100) COLLATE pg_catalog."default",
    username character varying(100) COLLATE pg_catalog."default",
    password character varying(100) COLLATE pg_catalog."default",
    opsions character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT login_pkey PRIMARY KEY (id_login)
);

CREATE TABLE IF NOT EXISTS public.peminjaman_buku
(
    no_peminjaman character varying(10) COLLATE pg_catalog."default" NOT NULL,
    status_peminjaman character varying(14) COLLATE pg_catalog."default",
    tgl_peminjaman_buku date,
    tgl_kembali_buku date,
    id_pengguna character varying(100) COLLATE pg_catalog."default" NOT NULL,
    angkatan character varying(8) COLLATE pg_catalog."default",
    id_buku character varying(10) COLLATE pg_catalog."default" NOT NULL,
    judul_buku character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT detail_peminjaman_buku_pkey PRIMARY KEY (no_peminjaman, id_pengguna, id_buku)
);

CREATE TABLE IF NOT EXISTS public.peminjaman_skripsi
(
    no_peminjaman_skripsi character varying(10) COLLATE pg_catalog."default" NOT NULL,
    judul_skripsi character varying(50) COLLATE pg_catalog."default",
    status_peminjaman character varying(14) COLLATE pg_catalog."default",
    tgl_peminjaman_skripsi date,
    tgl_kembali_skripsi date,
    id_pengguna character varying(100) COLLATE pg_catalog."default" NOT NULL,
    angkatan character varying(10) COLLATE pg_catalog."default",
    id_skripsi character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT detail_peminjaman_skripsi_pkey PRIMARY KEY (no_peminjaman_skripsi, id_pengguna, id_skripsi)
);

CREATE TABLE IF NOT EXISTS public.pengguna
(
    id_pengguna character(100) COLLATE pg_catalog."default" NOT NULL,
    nim character varying(100) COLLATE pg_catalog."default",
    nama character varying(100) COLLATE pg_catalog."default",
    jurusan character varying(100) COLLATE pg_catalog."default",
    tempat_lahir character varying(100) COLLATE pg_catalog."default",
    tanggal_lahir character varying(100) COLLATE pg_catalog."default",
    username character varying(100) COLLATE pg_catalog."default",
    password character varying(100) COLLATE pg_catalog."default",
    alamat character varying(100) COLLATE pg_catalog."default",
    level character varying(100) COLLATE pg_catalog."default",
    jenis_kelamin character varying(100) COLLATE pg_catalog."default",
    telephone character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT pengguna_pkey PRIMARY KEY (id_pengguna)
);

CREATE TABLE IF NOT EXISTS public.skripsi
(
    id_skripsi character(11) COLLATE pg_catalog."default" NOT NULL,
    judul character varying(50) COLLATE pg_catalog."default",
    bahasa character varying(15) COLLATE pg_catalog."default",
    fakultas character varying(30) COLLATE pg_catalog."default",
    program_studi character varying(30) COLLATE pg_catalog."default",
    tahun character varying(4) COLLATE pg_catalog."default",
    penulis character varying(30) COLLATE pg_catalog."default",
    pembimbing character varying(30) COLLATE pg_catalog."default",
    jumlah_halaman character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT pk_skripsi PRIMARY KEY (id_skripsi)
);

ALTER TABLE IF EXISTS public.kategori_buku
    ADD CONSTRAINT fk_kategori_memiliki2_buku FOREIGN KEY (id_buku)
    REFERENCES public.buku (id_buku) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS memiliki20_fk
    ON public.kategori_buku(id_buku);


ALTER TABLE IF EXISTS public.kategori_buku
    ADD CONSTRAINT fk_kategori_memiliki2_kategori FOREIGN KEY (id_kategori)
    REFERENCES public.kategori (id_kategori) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS memiliki21_fk
    ON public.kategori_buku(id_kategori);


ALTER TABLE IF EXISTS public.kategori_skripsi
    ADD CONSTRAINT fk_kategori_memiliki2_kategori FOREIGN KEY (id_kategori)
    REFERENCES public.kategori (id_kategori) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS memiliki22_fk
    ON public.kategori_skripsi(id_kategori);


ALTER TABLE IF EXISTS public.kategori_skripsi
    ADD CONSTRAINT fk_kategori_memiliki2_skripsi FOREIGN KEY (id_skripsi)
    REFERENCES public.skripsi (id_skripsi) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS memiliki3_fk
    ON public.kategori_skripsi(id_skripsi);


ALTER TABLE IF EXISTS public.peminjaman_buku
    ADD CONSTRAINT fk_peminjam_melakukan_petugas FOREIGN KEY (id_pengguna)
    REFERENCES public.pengguna (id_pengguna) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.peminjaman_buku
    ADD CONSTRAINT fk_peminjaman_id_buku FOREIGN KEY (id_buku)
    REFERENCES public.buku (id_buku) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.peminjaman_skripsi
    ADD CONSTRAINT fk_peminjam_melakukan_petugas FOREIGN KEY (id_pengguna)
    REFERENCES public.pengguna (id_pengguna) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.peminjaman_skripsi
    ADD CONSTRAINT fk_peminjaman_id_skripsi FOREIGN KEY (id_skripsi)
    REFERENCES public.skripsi (id_skripsi) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;

END;